name: Switch
favicon: null
layout_spectrum: 0.172518621198833
typography_spectrum: 0.5823651526588947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3604368884116411
  lightness: 0.26059187902137637
  saturation: 0.8542616909835488
  rhythmicContrast: 0.747208186192438
purpose: []
